name: terraform CI

on:
  push:
    branches: ["*"] # run on all branches
  pull_request:
    branches: ["*"] # also run when people create PRs

jobs:
    terraform:
        name: terraform lint and validation
        runs-on: ubuntu-latest

        env:
            AWS_REGION: 'eu-north-1'
            TF_VERSION: '1.0'
            TFLINT_VERSION: '0.46.1'
            TFSEC_VERSION: '1.28.1'
        
        steps:
            - name: checkout to github repo
              uses: actions/checkout@v4

            - name: setup  terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: ${{ env.TF_VERSION}}

            - name: format Terraform files
              id: fmt_recursive
              run: terraform fmt -check # just check, do not change
              working-directory: terraform

            - name: Terraform Init
              run: terraform init -backend=false
              working-directory: terraform
            
            - name: Terraform Validate
              run: terraform validate
              working-directory: terraform